### ISSUE TITLE
Should we add the Linux submark legend to the title page of the documentation?

### ISSUE THREAD

**Issue by aclark801** [openela/openela-documentation#31]
OpenELA, today, was granted a sublicense to use the Linux trademark in connection with the OpenELA services, pursuant to [The Linux Mark Sublicense Agreement](https://www.linuxfoundation.org/legal/sublicense-agreement).

Section 3.1 of the agreement states, "Sublicensee is required to place the following legend conspicuously on all Authorized Goods/Services, and at least once in the area of the title page of any documentation or sales literature accompanying the Authorized Goods/Services:

“The registered trademark Linux® is used pursuant to a sublicense from the Linux Foundation, the exclusive licensee of Linus Torvalds, owner of the mark on a world­wide basis"

Do we already / Or should we add the legend to the title page?

**Comment by wsoyinka** [comment]
Thank you @aclark801 :-) 

Kindly add the reference number for the approval to this issue for posterity purposes.

**Comment by aclark801** [comment]
Here's the email notice we received from the LF containing the reference number:

"Dear Alan,

This email grants OpenEL Association a sublicense to use the Linux trademark as described in your email below in connection with the OpenELA services, pursuant to [The Linux Mark Sublicense Agreement](https://www.linuxfoundation.org/legal/sublicense-agreement). Please be sure to review the Agreement and to comply with its terms, including, without limitation, the notice requirements in Section 3.1.  See https://www.linuxfoundation.org/legal/the-linux-mark for more information on the sublicense program.

The reference number is 20240829-0001.  Please reference this number in any correspondence regarding your sublicense.

Sincerely,
Daniel

Daniel L. Scales
Chief Brand Counsel

[dscales@linuxfoundation.org](mailto:dscales@linuxfoundation.org)
Note: Upcoming out of office: September 5-8
General trademark inbox: [tm@linuxfoundation.org](mailto:tm@linuxfoundation.org)

**Comment by ol-roboro** [comment]
I have submitted the PRs for this. I think we should possibly get this checked by someone in legal to make sure that they are happy with how we are approaching this. @aclark801 I don't know if you can get somebody to confirm that this change is appropriate.

**Comment by dirkmueller** [comment]
all merged, thanks @aclark801 and @ol-roboro !
